name: Release

on:
  push:
    branches: [main]

permissions: {}

concurrency:
  group: main-${{ github.repository }}
  cancel-in-progress: false
  queue: max

jobs:
  verify:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    permissions:
      contents: read
    uses: ./.github/workflows/verify.yml

  release:
    needs: [verify]
    permissions:
      contents: read
      id-token: write
    uses: uinaf/.github/.github/workflows/release-npm.yml@906e5111d19132ce85765cdc5ed28c9a87381d4b # v3.0.1
    secrets:
      UINAF_CI_APP_PRIVATE_KEY: ${{ secrets.UINAF_CI_APP_PRIVATE_KEY }}
