name: Release

on:
  push:
    branches: [main]

permissions: {}

concurrency:
  group: main-${{ github.repository }}
  cancel-in-progress: false

jobs:
  verify:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    permissions:
      contents: read
    uses: ./.github/workflows/verify.yml

  scan:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    permissions:
      contents: read
    uses: uinaf/.github/.github/workflows/scan.yml@168dfda80c93edc6c7085675e0982e32e2229c97 # v1.0.2

  release:
    needs: [verify, scan]
    permissions:
      contents: read
      id-token: write
    uses: uinaf/.github/.github/workflows/release-npm.yml@168dfda80c93edc6c7085675e0982e32e2229c97 # v1.0.2
    secrets:
      UINAF_CI_APP_PRIVATE_KEY: ${{ secrets.UINAF_CI_APP_PRIVATE_KEY }}
